spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.hzit.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-provider-8001-dev   #为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/myschool
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka # eureka服务器的地址   单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance: 
    instance-id: springcloud-dept  #设置访问的别名
    prefer-ip-address: true        #显示ip地址
info:                              #点击别名  访问info信息
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001

mybatis:
  type-aliases-package: com.hzit.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-provider-8001-test   #为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/myschool
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka # eureka服务器的地址   单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance: 
    instance-id: springcloud-dept  #设置访问的别名
    prefer-ip-address: true        #显示ip地址
info:                              #点击别名  访问info信息
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$